name: CI Build
on:
  push:
    branches: [ main ]
  workflow_call: 

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REPOSITORY: ${{ github.repository }}
  CONTAINER_IMAGE_PATH: ghcr.io/${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create docker image tag
        id: tag
        run: echo "::set-output name=tag::$(date -u +'%Y%m%d%H%M%S')"

      - name: Set up QEMU
        with:
          platforms: amd64,arm64
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: ${{env.CONTAINER_IMAGE_PATH}}:dev-${{ steps.tag.outputs.tag }}

