name: Publish release to dockerhub
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract version from release tag
        id: version
        run: echo "::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 4)"

      - name: Run tests
        run: |
          echo "Running tests..."
          VERSION=${{ steps.version.outputs.version }} ./tests/check-tag.sh
          echo "Tests passed"

        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: dajudge/tunnel-ingress:${{ steps.version.outputs.version }}

