name: Publish release to dockerhub
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create docker image tag
        id: tag
        run: echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 4)"
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tunnel-ingress:${{ steps.tag.outputs.tag }} .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Push to Docker Hub
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/tunnel-ingress:${{ steps.tag.outputs.tag }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}